### ISSUE TITLE
publish nuget package to myget

### ISSUE THREAD

**Issue by ErikEJ** [crhairr/EntityFrameworkCore.MongoDb#2]
Otherwise too hard to get started

**Comment by crhairr** [comment]
I agree. It's on my backlog to publish an initial preview build and then get a serviceable CI in place. I haven't decided if I should stay in step with EFCore build numbers or start over from 0.1.0-preview and let this provider be its own thing from a version perspective.

**Comment by ErikEJ** [comment]
Starting the alpha's with low numbers makes sense, for release I suggest keeping in sync with EF Core. Let me know if you need any help with build and release, happy to assist.

**Comment by crhairr** [comment]
I'm open to any suggestions for CI tools, especially anything that integrates with GitHub. I'm just getting this whole process started and I'd like to automate as much of it as possible so I can focus on code (including the consuming project I wrote this for in the first place!).

**Comment by ErikEJ** [comment]
For the SQLCE EF Provider, I use AppVeyor for builds and MyGet for NuGet hosting, both have free plans for open source projects, and both work flawlessly

**Comment by crhairr** [comment]
You weren't kidding. AppVeyor took less than 5 minutes to set up. I'll work on getting MyGet up and running today and get that initial package out. Thanks!

**Comment by crhairr** [comment]
The first package has been published to the new [efcore-mongodb MyGet feed](https://www.myget.org/F/efcore-mongodb/api/v3/index.json)!

**Comment by ErikEJ** [comment]
Fantastic! So the only missing piece for someone like me to get started would be a Quick start guide on the Wiki, with pointers to official MongoDb docs for deeper info.
Ie: 
- Blogs and Posts classes
- Create database (maybe not possible with EF atm?)
- Connect
- Add data
- Query
